<script src="./手写promise.js"></script>
<script>
  const promise = new MyPromise((resolve, reject) => {
    resolve('123')
  })
  promise.then((res) => {
    console.log(res, 'then1')
    return new MyPromise((re) => {
      re(1)
    })
  }).then((res) => {
    console.log(res, 'then2')
  })

  // Promise.reject().then((res) => {
  //   console.log(res, 'reject')
  // })

  MyPromise.resolve(1).then((res) => {
    console.log(1, 'resolve1')
    return res
  }).then((res) => {
    console.log(res, 'resolve2')
    return res
  }).then((res) => {
    console.log(res, 'resolve3')
  })

  MyPromise.reject(1).then((res) => {
    console.log(res, 'reject1')
  }, (rej) => {
    console.log(rej, 'reject2')
  })

  MyPromise.resolve(22).then((res) => {
    console.log(res, 'catch1')
    throw new Error()
  }).catch((err) => {
    console.log(err, 'catch2')
  })

  const p1 = new MyPromise((resolve, reject) => {
    reject('cc')
  })
  p1.catch((err) => {
    cosole.log(err, 'p1err')
  })

  const p2 = new Promise((resolve, reject) => {
    reject('cc')
  })
  p2.catch((err) => {
    console.log(err, 'p2err')
  })

  const promise1 = new Promise((resolve) => {
    resolve(1)
  })
  const promise2 = new Promise((resolve, reject) => {
    reject(2)
  })
  const promises = ['a', promise1, 'b', promise2]
  Promise.all(promises).then((res) =>{
    console.log(res, 'res')
  }, (err) => {
    console.log(err, 'rrrr')
  }).catch((err) =>{
    console.log(err, 'err')
  })

  const pp1 = new MyPromise((resolve) => {
    setTimeout(() => {
      resolve('pp1')
    }, 2000)
  })
  const pp2 = new MyPromise((resolve, reject) => {
    setTimeout(() => {
      resolve('pp2')
    }, 1000)
  })
  const pps = [pp1, pp2]
  MyPromise.all(pps).then((res) => {
    console.log(res, 'ppres')
  })
</script>