<script>
    try {
        throw new Error('foo')
    } catch (err) {
        console.log(err)
    }
</script>